<?php


namespace NovemBit\i18n\test;


use Exception;
use NovemBit\i18n\system\Component;

/**
 * @property  Test context
 */
class HTML extends Component
{

    private $nodes
        = [
            '<input type="submit" class="search-submit" value="Search">',
//            '<a href="hello/good">ayo</a>',
//
//            '<title>auuu</title>',
//            '<a>Test</a>',
//            '<a>Test <b>subtest</b></a>'
        ];

    /**
     * @param       $log
     * @param array $class
     * @param       $return
     *
     * @return mixed|string|null
     */
    public function log($log, $class = [], $return = false)
    {
        return $this->context->log($log, $class, $return);
    }

    /**
     * @return string
     * @throws Exception
     */
    private function test()
    {
        $log         = '';
        $translation = $this->context->context->translation;

        $result = $translation->setLanguages(['fr'])->html->translate(
            $this->nodes
        );

        foreach ($result as $source => $value) {
            $log .= $this->log(implode('',
                [
                    $source,
                    $this->log(
                        htmlentities($value['fr'], ENT_COMPAT, 'UTF-8'),
                        ['code'],
                        true
                    )
                ]
            ), ['code'], true);
        }

        return $log;
    }

    /**
     * @throws Exception
     */
    public function start()
    {

        $this->log(self::class . ' Testing' . $this->test(), ['code']);


        parent::init(); // TODO: Change the autogenerated stub

    }
}