<?php


namespace NovemBit\i18n\test;


use NovemBit\i18n\Module;
use NovemBit\i18n\system\Component;

/**
 * @property  Module context
 * @property  URL    url
 * @property  Language language
 * @property  HTML html
 * @property  HTMLParser html_parser
 * @property  Text text
 * @property  JSON json
 */
class Test extends Component
{

    public function log($log, $class, $return = false)
    {
        if ( ! is_string($log)) {
            $log = var_export($log, true);
        }

        if(is_string($class)){
            $class = [$class];
        }
        $class[] = 'row';
        $class = implode(' ', $class);

        $log   = '<div class="' . $class . '">' . htmlspecialchars($log ). '</div>';

        if ($return == true) {
            return $log;
        } else {
            echo $log;

            return null;
        }
    }

    public function start()
    {

        $this->enqueueStyle();

        $this->log(self::class . ' Testing',['code']);

        if(isset($_GET['type'])){
            $this->{$_GET['type']}->start();
        }

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function enqueueStyle()
    {
        echo <<<style
<style>
.code {
    white-space: pre;
    font-family: monospace;
    letter-spacing: 0.4;
    }
.row {
    margin: 10px 25px;
    padding: 10px;
    background: #00000017;
    border-bottom:dashed 1px #999;
}
</style>
style;

    }
}