<?php

namespace NovemBit\i18n\component\translation\type;

use Exception;
use NovemBit\i18n\component\Translation;

/**
 * @property  Translation context
 */
class Text extends Type
{
    public $type = 1;

    public $validation = true;

    public $dont_translate_patterns = [

        /*
         * Dont translate texts that contains less then 3 characters
         * Or not contains letters
         * */
        '^(([^\p{L}]+)|(.{1,2}))$'
    ];
	/**
	 * @param array $texts
	 *
	 * @return array
	 * @throws Exception
	 */
	public function doTranslate(array $texts){

		$translations = $this->context->method->translate($texts);
		foreach ($translations as $source => &$translation){
		    foreach ($translation as $language => &$text){
		        $text = htmlspecialchars_decode($text,ENT_QUOTES | ENT_HTML401 );
            }
        }
		return $translations;
	}

	public function validateBeforeTranslate(&$text)
    {

        foreach($this->dont_translate_patterns as $pattern){
            if(preg_match("/$pattern/",$text)){

                return false;
            }
        }

        return parent::validateBeforeTranslate($text); // TODO: Change the autogenerated stub
    }
}