<?php

namespace NovemBit\i18n\component\translation\type;

use Exception;
use NovemBit\i18n\component\Translation;

/**
 * @property  Translation context
 */
class URL extends Type
{

    public $type = 2;

    public $path_separator = "-";

    public $path_lowercase = true;

    public $alias_domains = [];

    public $validation = true;

    public $url_validation_rules
        = [
            'host' => [
                '^$|^swanson\.co\.uk$',
            ],
            'path' => ['^(?!^\/$).+$'],
        ];


    /**
     * @param array $urls
     *
     * @return array
     * @throws Exception
     */
    public function doTranslate(array $urls)
    {

        $languages          = $this->context->getLanguages();
        $paths              = [];
        $paths_to_translate = [];

        foreach ($urls as $url) {
            $parts              = $this->getUrlParts($url);
            $path               = isset($parts['path']) ? $parts['path'] : "";
            $to_translate       = $this->getPathParts($path);
            $paths[]            = $to_translate;
            $paths_to_translate = array_merge($paths_to_translate, $to_translate);
        }

        $translations = $this->getPathPartTranslations($paths_to_translate);

        $result = $this->buildTranslateResult($paths, $languages, $translations);

        return $result;
    }

    /**
     * @param $before
     * @param $after
     * @param $translates
     *
     * @return bool
     */
    public function validateAfter($before, $after, &$translates)
    {
        $prefix = $before;
        $suffix = '';

        if ($after != '') {
            $pos    = strpos($before, $after);
            $prefix = substr($before, 0, $pos);
            $suffix = substr(
                $before,
                strlen($prefix) +
                strlen($after),
                strlen($before)
            );
        }


        if ($before != $after && isset($translates[$after])) {
            $translates[$before] = $translates[$after];
            foreach ($translates[$before] as $language => &$translate) {
                $translate = $prefix . $language . '/' . $translate . $suffix;
            }
            unset($translates[$after]);
        }

        return  parent::validateAfter($before, $after, $translates); // TODO: Change the autogenerated stub
    }

    /**
     * @param $url
     *
     * @return bool
     */
    public function validateBefore(&$url)
    {

        $url = $this->context->context->languages->removeScriptNameFromUrl($url);

        $url = parse_url($url, PHP_URL_PATH);

        $url = rtrim($url, '/');

        $parts = parse_url($url);

        foreach ($this->url_validation_rules as $key => $rules) {
            if ( ! isset($parts[$key])) {
                $parts[$key] = '';
            }
            foreach ($rules as $rule) {
                if ( ! preg_match("/$rule/", $parts[$key])) {
                    return false;

                }
            }
        }

        return true;

    }

    /**
     * @param array $paths
     * @param array $languages
     * @param array $translations
     *
     * @return array
     */
    private function buildTranslateResult(
        array $paths,
        array $languages,
        array $translations
    ) {

        $result = [];

        foreach ($paths as $path_parts) {

            $path = implode('/', $path_parts);
            /*
             * To build last result fetching languages
             * And building result with language keys
             * */
            foreach ($languages as $language) {

                $language_path_parts = $path_parts;

                foreach ($language_path_parts as &$part) {

                    $part = $translations[$part][$language];

                    /**
                     * If translator returns string that contains
                     * Unwanted characters, then clarifying string
                     * */
                    $part = $this->preparePathPart($part);
                }

                /**
                 * Restore path trailing slashes
                 * */
                $translate = implode('/', $language_path_parts);

                /*
                 * Appending translated url to result
                 * */
                $result[$path][$language] = $translate;
            }
        }

        return $result;
    }

    /**
     * @param array $strings
     *
     * @return mixed
     * @throws Exception
     */
    private function getPathPartTranslations(array $strings)
    {

        $translate = $this->context->text->translate($strings);

        return $translate;
    }

    /**
     * Get path parts slash delimited
     *
     * @param $path
     *
     * @return array
     */
    private function getPathParts($path)
    {

        $path = trim($path, '/');

        /*
         * Separate path parts
         * */
        $parts = explode('/', $path);

//        foreach ($parts as &$part) {
//
//            /*
//             * Clarify parts
//             * Remove unwanted characters
//             * */
//            $part = $this->preparePathPart($part);
//        }

        return $parts;
    }

    /**
     * @param $url
     *
     * @return mixed
     */
    private function getUrlParts($url)
    {
        $parts = parse_url($url);

        return $parts;
    }

    /**
     * @param $string
     *
     * @return string|null
     */
    private function preparePathPart($string)
    {
        /**
         * Remove all html special characters
         * @source https://stackoverflow.com/a/657670
         * */
        $string = preg_replace("/&#?[a-z0-9]{2,8};/i", "", $string);

        /**
         * Replace all non-alphanumeric characters to whitespace
         * To make url SEO friendly
         * */
        $string = preg_replace('/(?:\W|_)+/u', $this->path_separator, $string);

        /**
         * Remove "-" symbol from start and end of string
         * */
        $string = trim($string, $this->path_separator);

        if ($this->path_lowercase !== false) {
            /**
             * String to lowercase
             * */
            $string = strtolower($string);
        }

        return $string;
    }
}