<?php
/**
 * Main i18n module
 * php version 7.2.10
 *
 * @category Component
 * @package  Composer
 * @author   Aaron Yordanyan <aaron.yor@gmail.com>
 * @license  https://www.gnu.org/licenses/gpl-3.0.txt GNU/GPLv3
 * @version  GIT: @1.0.1@
 * @link     https://github.com/NovemBit/i18n
 */

namespace NovemBit\i18n;

use Exception;

/**
 * Module class
 *
 * @property component\Translation translation
 * @property component\Languages languages
 * @property component\Request request
 * @property component\DB db
 * @property component\Rest rest
 */
class Module extends system\Component
{
    private static $instance;

    public $prefix = 'i18n';

    /**
     * Init for component
     *
     * @throws Exception
     */
    public function init()
    {

    }

    public function commonInit()
    {
        defined('YII_DEBUG') or define('YII_DEBUG', true);
        defined('YII_ENV') or define('YII_ENV', 'dev');

        include __DIR__ . '/../../../yiisoft/yii2/Yii.php';

        parent::commonInit(); // TODO: Change the autogenerated stub
    }

    /**
     * Start request translation
     *
     * @throws Exception
     */
    public function start()
    {
        $this->rest->start();
        $this->request->start();
    }

    /**
     * Creating module main instance
     *
     * @param null $config
     * @return Module
     */
    public static function instance($config = null)
    {

        if (!isset(self::$instance) && ($config != null)) {
            self::$instance = new self($config);
        }

        return self::$instance;
    }

}